name: Build job container
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      stackTag:
        description: 'Science Pipelines tag'
        required: true
        default: 'w_latest'
        type: string

jobs:
  build-image:
    name: Build image for nightly reporting
    runs-on: ubuntu-latest
    env:
      STACK_TAG: ${{ inputs.stackTag || 'w_latest' }}
      IMAGE_ID: "ghcr.io/${{ github.repository_owner }}/nightly-reporting"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: "${{ env.IMAGE_ID }}:${{ env.STACK_TAG }}"
          labels: |
            "runnumber=${{ github.run_id }}"
            "stacktag=${{ env.STACK_TAG }}"
          build-args: |
            STACK_TAG=${{ env.STACK_TAG }}
