name: Build job container
on:
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
    inputs:
      stackTag:
        description: 'Science Pipelines tag'
        required: true
        default: 'w_latest'
        type: string

jobs:
  build-image:
    name: Build image for nightly reporting
    runs-on: ubuntu-latest
    env:
      STACK_TAG: ${{ inputs.stackTag || 'w_latest' }}
      IMAGE_NAME: nightly-reporting
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build image
        run: |
          docker build . -f Dockerfile \
            --build-arg "STACK_TAG=${STACK_TAG}" \
            --tag $IMAGE_NAME \
            --label "runnumber=${GITHUB_RUN_ID}" \
            --label "stacktag=${STACK_TAG}" \
      - name: Push image to registries
        run: |
          echo STACK_TAG=$STACK_TAG
          IMAGE_ID="ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME"
          docker tag $IMAGE_NAME $IMAGE_ID:$STACK_TAG
          docker push $IMAGE_ID:$STACK_TAG
